# trusty beta image has jdk8, gcc4.8.4
dist: trusty
sudo: required
# xcode8 has jdk8
osx_image: xcode8.3
# Not technically required but suppresses 'Ruby' in Job status message.
language: java

os:
  - linux
#  - osx

env:
  global:
    - V=0.21.0
  matrix:
    - TEST=bazel
    - TEST=inMemoryBootstrap
    - TEST=inMemoryRestart
    - TEST=remoteRestart
    - TEST=remoteLayerCalculation


addons:
  apt:
    packages:
      - jq

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      OS=darwin
    else
      OS=linux
    fi
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

script:
  - |
    if [[ "${TEST}" == "bazel" ]]; then
      bazel \
          --output_base=$HOME/.cache/bazel \
          --host_jvm_args=-Xmx500m \
          --host_jvm_args=-Xms500m \
          test \
          --config=ci \
          --experimental_repository_cache="$HOME/.bazel_repository_cache" \
          --local_resources=400,1,1.0 \
          //...
    fi
  # run HOW TO steps
  - |
    if [[ "${TEST}" != "bazel" ]]; then
      /bin/sh CI/setupTests.sh;
      /bin/sh CI/${TEST}.sh;
      sudo /bin/sh CI/cleanUp.sh;
    fi

notifications:
  email: false
